<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>IcyClawz.ItemSellPrice</AssemblyName>
    <Version>1.7.0</Version>
    <RootNamespace>IcyClawz.ItemSellPrice</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(SptManaged)\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(SptBepInEx)\core\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="Comfort">
      <HintPath>$(SptManaged)\Comfort.dll</HintPath>
    </Reference>
    <Reference Include="SPT.Reflection">
      <HintPath>$(SptBepInEx)\plugins\spt\spt-reflection.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(SptManaged)\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(SptManaged)\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
